name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io

jobs:

  build-and-push-image:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: aws-cli
            dockerfile: ./aws-cli/Dockerfile
            image: ghcr.io/credibleforce/proxychains-aws-cli
          - context: azure-cli
            dockerfile: ./azure-cli/Dockerfile
            image: ghcr.io/credibleforce/proxychains-azure-cli
          - context: gcp-cli
            dockerfile: ./gcp-cli/Dockerfile
            image: ghcr.io/credibleforce/proxychains-gcp-cli
          - context: python
            dockerfile: ./python/Dockerfile
            image: ghcr.io/credibleforce/proxychains-python
          - context: hydra
            dockerfile: ./hydra/Dockerfile
            image: ghcr.io/credibleforce/proxychains-hydra
          - context: nmap
            dockerfile: ./nmap/Dockerfile
            image: ghcr.io/credibleforce/proxychains-nmap
          - context: scoutsuite-aws
            dockerfile: ./scoutsuite-aws/Dockerfile
            image: ghcr.io/credibleforce/proxychains-scoutsuite-aws
          - context: scoutsuite-azure
            dockerfile: ./scoutsuite-azure/Dockerfile
            image: ghcr.io/credibleforce/proxychains-scoutsuite-azure
          - context: scoutsuite-gcp
            dockerfile: ./scoutsuite-gcp/Dockerfile
            image: ghcr.io/credibleforce/proxychains-scoutsuite-gcp
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
