name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: proxychains

jobs:

  build-and-push-image:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: aws-cli
            dockerfile: ./src/aws-cli/Dockerfile
            image: ghcr.io/credibleforce/$IMAGE_NAME-aws-cli
          - context: azure-cli
            dockerfile: ./src/azure-cli/Dockerfile
            image: ghcr.io/credibleforce/$IMAGE_NAME-azure-cli
          - context: gcp-cli
            dockerfile: ./src/gcp-cli/Dockerfile
            image: ghcr.io/credibleforce/$IMAGE_NAME-gcp-cli
          - context: python
            dockerfile: ./src/python/Dockerfile
            image: ghcr.io/credibleforce/$IMAGE_NAME-python
          - context: hydra
            dockerfile: ./src/hydra/Dockerfile
            image: ghcr.io/credibleforce/$IMAGE_NAME-hydra
          - context: scoutsuite-aws
            dockerfile: ./src/scoutsuite-aws/Dockerfile
            image: ghcr.io/credibleforce/$IMAGE_NAME-scoutsuite-aws
          - context: scoutsuite-azure
            dockerfile: ./src/scoutsuite-azure/Dockerfile
            image: ghcr.io/credibleforce/$IMAGE_NAME-scoutsuite-azure
          - context: scoutsuite-gcp
            dockerfile: ./src/scoutsuite-gcp/Dockerfile
            image: ghcr.io/credibleforce/$IMAGE_NAME-scoutsuite-gcp
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image
        uses: docker/build-push-action
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
